"""Add missing columns and initial tables

Revision ID: 843237f3c528
Revises: 
Create Date: 2026-04-30 11:16:01.715996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843237f3c528'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pro_aula_segura_estudiantes', sa.Column('fecha_descargados', sa.String(length=20), nullable=True))
    op.alter_column('pro_aula_segura_estudiantes', 'fecha_recepcion_apelacion',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('pro_aula_segura_estudiantes', 'fecha_consejo_profesores',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pro_aula_segura_estudiantes', 'fecha_consejo_profesores',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('pro_aula_segura_estudiantes', 'fecha_recepcion_apelacion',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('pro_aula_segura_estudiantes', 'fecha_descargados')
    # ### end Alembic commands ###
